server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:mem:pokrew
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

logging:
  level:
    com.pokrew.server: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: "pokrewSecretKeyForJWTTokenGeneration2023!"
  expiration: 86400000 # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    mappings:
      enabled: true
